#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -DMAXENTMC_CACHE_LINE_SIZE=`getconf LEVEL1_DCACHE_LINESIZE`
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)-lgsl -lgslcblas
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/test_maxentmc

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -fomit-frame-pointer -O2 -fPIC
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/libmaxentmc.so

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/user/maxentmc_quad_rectangle_uniform.o $(OBJDIR_DEBUG)/src/user/maxentmc_basic_algorithm.o $(OBJDIR_DEBUG)/src/tests/test_vector.o $(OBJDIR_DEBUG)/src/tests/test_quad_gauss_1D.o $(OBJDIR_DEBUG)/src/tests/test_quad.o $(OBJDIR_DEBUG)/src/tests/test_maxentmc_simple.o $(OBJDIR_DEBUG)/src/tests/test_list.o $(OBJDIR_DEBUG)/src/tests/test_gradient_hessian.o $(OBJDIR_DEBUG)/src/tests/main.o $(OBJDIR_DEBUG)/src/core/maxentmc_vector.o $(OBJDIR_DEBUG)/src/core/maxentmc_symmeig.o $(OBJDIR_DEBUG)/src/core/maxentmc_quad_helper.o $(OBJDIR_DEBUG)/src/core/maxentmc_power.o $(OBJDIR_DEBUG)/src/core/maxentmc_list.o $(OBJDIR_DEBUG)/src/core/maxentmc_gradient_hessian.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/core/maxentmc_vector.o $(OBJDIR_RELEASE)/src/core/maxentmc_symmeig.o $(OBJDIR_RELEASE)/src/core/maxentmc_quad_helper.o $(OBJDIR_RELEASE)/src/core/maxentmc_power.o $(OBJDIR_RELEASE)/src/core/maxentmc_list.o $(OBJDIR_RELEASE)/src/core/maxentmc_gradient_hessian.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/user || mkdir -p $(OBJDIR_DEBUG)/src/user
	test -d $(OBJDIR_DEBUG)/src/tests || mkdir -p $(OBJDIR_DEBUG)/src/tests
	test -d $(OBJDIR_DEBUG)/src/core || mkdir -p $(OBJDIR_DEBUG)/src/core

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/user/maxentmc_quad_rectangle_uniform.o: src/user/maxentmc_quad_rectangle_uniform.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/user/maxentmc_quad_rectangle_uniform.c -o $(OBJDIR_DEBUG)/src/user/maxentmc_quad_rectangle_uniform.o

$(OBJDIR_DEBUG)/src/user/maxentmc_basic_algorithm.o: src/user/maxentmc_basic_algorithm.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/user/maxentmc_basic_algorithm.c -o $(OBJDIR_DEBUG)/src/user/maxentmc_basic_algorithm.o

$(OBJDIR_DEBUG)/src/tests/test_vector.o: src/tests/test_vector.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/test_vector.c -o $(OBJDIR_DEBUG)/src/tests/test_vector.o

$(OBJDIR_DEBUG)/src/tests/test_quad_gauss_1D.o: src/tests/test_quad_gauss_1D.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/test_quad_gauss_1D.c -o $(OBJDIR_DEBUG)/src/tests/test_quad_gauss_1D.o

$(OBJDIR_DEBUG)/src/tests/test_quad.o: src/tests/test_quad.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/test_quad.c -o $(OBJDIR_DEBUG)/src/tests/test_quad.o

$(OBJDIR_DEBUG)/src/tests/test_maxentmc_simple.o: src/tests/test_maxentmc_simple.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/test_maxentmc_simple.c -o $(OBJDIR_DEBUG)/src/tests/test_maxentmc_simple.o

$(OBJDIR_DEBUG)/src/tests/test_list.o: src/tests/test_list.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/test_list.c -o $(OBJDIR_DEBUG)/src/tests/test_list.o

$(OBJDIR_DEBUG)/src/tests/test_gradient_hessian.o: src/tests/test_gradient_hessian.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/test_gradient_hessian.c -o $(OBJDIR_DEBUG)/src/tests/test_gradient_hessian.o

$(OBJDIR_DEBUG)/src/tests/main.o: src/tests/main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tests/main.c -o $(OBJDIR_DEBUG)/src/tests/main.o

$(OBJDIR_DEBUG)/src/core/maxentmc_vector.o: src/core/maxentmc_vector.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/core/maxentmc_vector.c -o $(OBJDIR_DEBUG)/src/core/maxentmc_vector.o

$(OBJDIR_DEBUG)/src/core/maxentmc_symmeig.o: src/core/maxentmc_symmeig.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/core/maxentmc_symmeig.c -o $(OBJDIR_DEBUG)/src/core/maxentmc_symmeig.o

$(OBJDIR_DEBUG)/src/core/maxentmc_quad_helper.o: src/core/maxentmc_quad_helper.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/core/maxentmc_quad_helper.c -o $(OBJDIR_DEBUG)/src/core/maxentmc_quad_helper.o

$(OBJDIR_DEBUG)/src/core/maxentmc_power.o: src/core/maxentmc_power.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/core/maxentmc_power.c -o $(OBJDIR_DEBUG)/src/core/maxentmc_power.o

$(OBJDIR_DEBUG)/src/core/maxentmc_list.o: src/core/maxentmc_list.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/core/maxentmc_list.c -o $(OBJDIR_DEBUG)/src/core/maxentmc_list.o

$(OBJDIR_DEBUG)/src/core/maxentmc_gradient_hessian.o: src/core/maxentmc_gradient_hessian.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/core/maxentmc_gradient_hessian.c -o $(OBJDIR_DEBUG)/src/core/maxentmc_gradient_hessian.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/user
	rm -rf $(OBJDIR_DEBUG)/src/tests
	rm -rf $(OBJDIR_DEBUG)/src/core

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/core || mkdir -p $(OBJDIR_RELEASE)/src/core

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/core/maxentmc_vector.o: src/core/maxentmc_vector.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/core/maxentmc_vector.c -o $(OBJDIR_RELEASE)/src/core/maxentmc_vector.o

$(OBJDIR_RELEASE)/src/core/maxentmc_symmeig.o: src/core/maxentmc_symmeig.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/core/maxentmc_symmeig.c -o $(OBJDIR_RELEASE)/src/core/maxentmc_symmeig.o

$(OBJDIR_RELEASE)/src/core/maxentmc_quad_helper.o: src/core/maxentmc_quad_helper.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/core/maxentmc_quad_helper.c -o $(OBJDIR_RELEASE)/src/core/maxentmc_quad_helper.o

$(OBJDIR_RELEASE)/src/core/maxentmc_power.o: src/core/maxentmc_power.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/core/maxentmc_power.c -o $(OBJDIR_RELEASE)/src/core/maxentmc_power.o

$(OBJDIR_RELEASE)/src/core/maxentmc_list.o: src/core/maxentmc_list.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/core/maxentmc_list.c -o $(OBJDIR_RELEASE)/src/core/maxentmc_list.o

$(OBJDIR_RELEASE)/src/core/maxentmc_gradient_hessian.o: src/core/maxentmc_gradient_hessian.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/core/maxentmc_gradient_hessian.c -o $(OBJDIR_RELEASE)/src/core/maxentmc_gradient_hessian.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/core

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

